package com.example.charl.hexagonwellness;

import android.content.Intent;
import android.net.Uri;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;

public class BookMassage extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_book_massage);


        final ImageButton calendarButton = findViewById(R.id.btn_calendar);
        calendarButton.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {

                Intent calIntent = new Intent(getApplicationContext(), Calendar.class);
                startActivity(calIntent);
                finish();
            }
        });

        final ImageButton bookButton = findViewById(R.id.btn_book_massage);
        bookButton.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                Intent bookIntent = new Intent(getApplicationContext(), BookMassage.class);
                startActivity(bookIntent);
                finish();
            }
        });
        final ImageButton hourButton = findViewById(R.id.btn_hour);
        hourButton.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                Intent hourIntent = new Intent(getApplicationContext(), Hours.class);
                startActivity(hourIntent);
                finish();
            }
        });
        final ImageButton adviceButton = findViewById(R.id.btn_advice);
        adviceButton.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                Intent blogIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("https://trueblue.intergraph.com/wellness/"));
                startActivity(blogIntent);
            }
        });
        final ImageButton recipeButton = findViewById(R.id.btn_recipe);
        recipeButton.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                Intent recipesIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("https://trueblue.intergraph.com/wellness/recipes.asp"));
                startActivity(recipesIntent);
            }
        });

        final Button sendEmailButton = findViewById(R.id.btn_send);
        sendEmailButton.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                Intent sendIntent = new Intent(Intent.ACTION_SEND);
                final EditText et_name = findViewById(R.id.txt_name);
                final EditText et_email = findViewById(R.id.txt_email);
                final EditText et_desired_time = findViewById(R.id.txt_desired_time);
                final EditText et_num_sessions = findViewById(R.id.txt_number_sessions);

                String name = et_name.getText().toString();
                String email = et_email.getText().toString();
                String desiredTime = et_desired_time.getText().toString();
                String numSessions = et_num_sessions.getText().toString();

                String subject, body;

                subject = "Massage request from " + name;

                body = "This message generated by HexFit. Hello, my name is " + name + ", and my company email is " + email + " and I would like to request " + numSessions + " massage(s). My availabilities are " + desiredTime + ". Thanks, " + name;

                sendIntent.putExtra(Intent.EXTRA_EMAIL, "trent.ford@hexagon.com");
                sendIntent.putExtra(Intent.EXTRA_SUBJECT, subject);
                sendIntent.putExtra(Intent.EXTRA_TEXT, body);

                sendIntent.setType("message/rfc822");

                startActivity(Intent.createChooser(sendIntent, "Choose an email client"));
            }
        });
    }
}
